name: Generate Podcast Feeds
on: [push]
jobs:
  build : 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generartor
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name Ramesh Thapa
          git config user.email Thapa.ramesh474@outlook.com
          git add .
          git commit -m "Modified Feed"
          git push
          
          
          
